name: .NET

on:
 push:
 pull_request:
  branches:
    - main
 workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      WORKDIR: ./src/HelloWorld
      AZURE_FUNCTIONAPP_NAME: "github-actions-workshop-5"
    defaults:
      run:
        working-directory: ${{env.WORKDIR}}

    steps:
    - name: "Checkout"
      uses: actions/checkout@v2.4.2
     
    - name: Setup .NET
      uses: actions/setup-dotnet@v2.1.0
      with:
        # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x
        dotnet-version: 6.0.x
#     - name: Build and Test a project
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Azure Functions Action
      uses: Azure/functions-action@v1.4.7
      with:
       # Name of the Azure Function App
       app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
      

